import { useCallback, useEffect, useMemo, useState } from 'react'
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { agentApi } from '../../src/agent/api'
import type { AgentHomeSnapshot, AgentRun } from '../../src/agent/types'
import { useTheme } from '../../src/theme'

export default function Activity(){const t=useTheme();const i=useSafeAreaInsets();const [snap,setSnap]=useState<AgentHomeSnapshot|null>(null);const [refreshing,setRefreshing]=useState(false);const refresh=useCallback(async()=>{try{setSnap(await agentApi.snapshot())}finally{setRefreshing(false)}},[]);useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),10000);return()=>clearInterval(id)},[refresh]);const working=useMemo(()=>(snap?.runs||[]).filter(x=>['queued','running','waiting_approval','paused'].includes(x.status)),[snap]);const done=useMemo(()=>(snap?.runs||[]).filter(x=>x.status==='completed').slice(0,8),[snap]);return <ScrollView style={{flex:1,backgroundColor:t.paper}} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void refresh()}}/>} contentContainerStyle={[s.wrap,{paddingTop:i.top+22,paddingBottom:96+i.bottom}]}><Text style={[s.title,{color:t.ink}]}>Activity</Text><Text style={[s.sub,{color:t.ink3}]}>Everything Gogo is doing, in detail</Text><GroupLabel color="#F26B1D" text={`WORKING · ${working.length}`}/>{working.map(r=><RunRow key={r.id} run={r}/>)}<GroupLabel color="#5B8DD6" text={`WATCHING · ${snap?.watchers.length||0}`}/>{snap?.watchers.map(w=><View key={w.id} style={[s.row,{borderBottomColor:t.rowLine}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:t.ink}]}>{w.title}</Text><Text style={[s.rowSub,{color:t.ink3}]}>{w.type.replaceAll('_',' ')} · every {w.cadenceMinutes} min</Text></View><Text style={[s.rowMeta,{color:t.ink3}]}>watching</Text></View>)}<GroupLabel color="#3DB283" text={`DONE TODAY · ${done.length}`}/>{done.map(r=><RunRow key={r.id} run={r}/>)}</ScrollView>}
function GroupLabel({color,text}:{color:string;text:string}){return <View style={s.group}><View style={[s.dot,{backgroundColor:color}]}/><Text style={[s.groupText,{color}]}>{text}</Text></View>}
function RunRow({run}:{run:AgentRun}){const t=useTheme();return <View style={[s.row,{borderBottomColor:t.rowLine}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:t.ink}]}>{run.title}</Text><Text style={[s.rowSub,{color:t.ink3}]}>{run.summary}</Text>{typeof run.progress==='number'?<View style={[s.track,{backgroundColor:t.surface}]}><View style={[s.fill,{width:`${Math.max(2,Math.min(100,run.progress))}%`} as any]}/></View>:null}</View><Text style={[s.rowMeta,{color:t.ink3}]}>{run.status.replaceAll('_',' ')}</Text></View>}
const s=StyleSheet.create({wrap:{paddingHorizontal:20},title:{fontSize:32,fontWeight:'700',letterSpacing:-.8},sub:{fontSize:12,marginTop:3,marginBottom:8},group:{flexDirection:'row',alignItems:'center',gap:6,marginTop:24,marginBottom:5},dot:{width:5,height:5,borderRadius:99},groupText:{fontSize:9,fontWeight:'800',letterSpacing:.75},row:{minHeight:62,flexDirection:'row',gap:14,alignItems:'flex-start',paddingVertical:13,borderBottomWidth:StyleSheet.hairlineWidth},rowTitle:{fontSize:14,fontWeight:'700'},rowSub:{fontSize:11,lineHeight:16,marginTop:4},rowMeta:{fontSize:9,maxWidth:70,textAlign:'right'},track:{height:3,borderRadius:99,overflow:'hidden',marginTop:9},fill:{height:'100%',backgroundColor:'#F26B1D',borderRadius:99}})