import { Ionicons } from '@expo/vector-icons'
import { useRouter } from 'expo-router'
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { ScreenTitle, SectionLabel, SettingRow } from '../../src/design/components'
import { useTheme } from '../../src/theme'

export default function Memory(){const t=useTheme();const r=useRouter();const i=useSafeAreaInsets();return <ScrollView style={{flex:1,backgroundColor:t.paper}} contentContainerStyle={[s.wrap,{paddingTop:i.top+28,paddingBottom:96+i.bottom}]}><ScreenTitle eyebrow="Memory" title="What Gogo remembers." body="Find something you saved, or capture new context in a few seconds."/><View style={[s.search,{backgroundColor:t.surface,borderColor:t.hairline}]}><Ionicons name="search-outline" size={19} color={t.ink3}/><TextInput placeholder="Search your memory" placeholderTextColor={t.ink3} style={[s.input,{color:t.ink}]}/></View><View style={s.captureRow}>{[['camera-outline','Photo'],['document-text-outline','Document'],['mic-outline','Voice'],['create-outline','Note']].map(([icon,label])=><Pressable key={label} onPress={()=>r.push('/capture')} style={s.capture}><View style={[s.captureIcon,{backgroundColor:t.surface}]}><Ionicons name={icon as any} size={21} color={t.ink2}/></View><Text style={[s.captureText,{color:t.ink2}]}>{label}</Text></Pressable>)}</View><SectionLabel>Spaces</SectionLabel><SettingRow icon="airplane-outline" title="Trips" subtitle="Plans, bookings and travel context" onPress={()=>r.push('/workspaces')}/><SettingRow icon="briefcase-outline" title="Work" subtitle="Projects and ongoing context" onPress={()=>r.push('/workspaces')}/><SettingRow icon="bookmark-outline" title="Saved context" subtitle="Things worth keeping" onPress={()=>r.push('/workspaces')}/></ScrollView>}
const s=StyleSheet.create({wrap:{paddingHorizontal:20},search:{height:52,borderWidth:1,borderRadius:16,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:10},input:{flex:1,fontSize:15},captureRow:{flexDirection:'row',justifyContent:'space-between',marginTop:22},capture:{alignItems:'center',width:'24%'},captureIcon:{width:48,height:48,borderRadius:15,alignItems:'center',justifyContent:'center'},captureText:{fontSize:11,marginTop:7}})
