import { useCallback, useEffect, useState } from 'react'
import { Ionicons } from '@expo/vector-icons'
import { useRouter } from 'expo-router'
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { agentApi } from '../../src/agent/api'
import type { AgentHomeSnapshot } from '../../src/agent/types'
import { Gogo } from '../../src/design/Gogo'
import { useTheme } from '../../src/theme'

export default function Memory(){const t=useTheme();const r=useRouter();const i=useSafeAreaInsets();const [snap,setSnap]=useState<AgentHomeSnapshot|null>(null);const [refreshing,setRefreshing]=useState(false);const refresh=useCallback(async()=>{try{setSnap(await agentApi.snapshot())}finally{setRefreshing(false)}},[]);useEffect(()=>{void refresh()},[refresh]);return <ScrollView keyboardDismissMode="on-drag" style={{flex:1,backgroundColor:t.paper}} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void refresh()}}/>} contentContainerStyle={[s.wrap,{paddingTop:i.top+22,paddingBottom:96+i.bottom}]}><View style={s.heading}><View><Text style={[s.title,{color:t.ink}]}>Memory</Text><Text style={[s.sub,{color:t.ink3}]}>What Gogo knows about your life</Text></View><Gogo state="remembering" size={48}/></View><View style={[s.search,{backgroundColor:t.surface}]}><Ionicons name="search-outline" size={18} color={t.ink3}/><TextInput placeholder="Search memory" placeholderTextColor={t.ink3} style={[s.input,{color:t.ink}]}/></View><Text style={[s.prompt,{color:t.ink}]}>Give Gogo something to remember</Text><View style={s.captureRow}>{[['camera-outline','Photo'],['document-text-outline','Document'],['mic-outline','Voice'],['create-outline','Note']].map(([icon,label])=><Pressable key={label} onPress={()=>r.push('/capture')} style={s.capture}><View style={[s.captureIcon,{backgroundColor:t.surface}]}><Ionicons name={icon as any} size={20} color={t.ink2}/></View><Text style={[s.captureText,{color:t.ink2}]}>{label}</Text></Pressable>)}</View><Text style={[s.section,{color:t.ink3}]}>RECENT</Text>{snap?.artifacts.length?snap.artifacts.slice(0,6).map(a=><MemoryRow key={a.id} icon={a.type==='trip'?'airplane-outline':'document-text-outline'} title={a.title} sub={a.subtitle||a.type.replaceAll('_',' ')}/>):<View style={s.empty}><Text style={[s.emptyText,{color:t.ink2}]}>No recent memory items yet.</Text></View>}<Text style={[s.section,{color:t.ink3}]}>SPACES</Text><MemoryRow icon="airplane-outline" title="Trips" sub="Travel plans, bookings and context" onPress={()=>r.push('/workspaces')}/><MemoryRow icon="briefcase-outline" title="Work" sub="Projects and ongoing context" onPress={()=>r.push('/workspaces')}/></ScrollView>}
function MemoryRow({icon,title,sub,onPress}:{icon:any;title:string;sub:string;onPress?:()=>void}){const t=useTheme();return <Pressable onPress={onPress} style={[s.row,{borderBottomColor:t.rowLine}]}><View style={[s.rowIcon,{backgroundColor:t.surface}]}><Ionicons name={icon} size={17} color={t.ink2}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:t.ink}]}>{title}</Text><Text style={[s.rowSub,{color:t.ink3}]}>{sub}</Text></View>{onPress?<Ionicons name="chevron-forward" size={16} color={t.ink3}/>:null}</Pressable>}
const s=StyleSheet.create({wrap:{paddingHorizontal:20},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},title:{fontSize:32,fontWeight:'700',letterSpacing:-.8},sub:{fontSize:12,marginTop:3},search:{height:42,borderRadius:14,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8,marginTop:18},input:{flex:1,fontSize:14},prompt:{fontSize:15,fontWeight:'700',marginTop:22},captureRow:{flexDirection:'row',justifyContent:'space-between',marginTop:14},capture:{alignItems:'center',width:'24%'},captureIcon:{width:46,height:46,borderRadius:15,alignItems:'center',justifyContent:'center'},captureText:{fontSize:10,marginTop:6},section:{fontSize:10,fontWeight:'800',letterSpacing:1,marginTop:26,marginBottom:4},row:{minHeight:60,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:StyleSheet.hairlineWidth},rowIcon:{width:36,height:36,borderRadius:11,alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:14,fontWeight:'600'},rowSub:{fontSize:10,marginTop:3},empty:{paddingVertical:18},emptyText:{fontSize:12}})
