import { useCallback, useEffect, useState } from 'react'
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { agentApi } from '../../src/agent/api'
import type { AgentConsumerHome, AgentHomeItem } from '../../src/agent/types'
import { Gogo, stateForHome, stateForItem } from '../../src/design/Gogo'
import { useTheme } from '../../src/theme'

export default function Today(){const t=useTheme();const i=useSafeAreaInsets();const [home,setHome]=useState<AgentConsumerHome|null>(null);const [refreshing,setRefreshing]=useState(false);const refresh=useCallback(async()=>{try{setHome(await agentApi.home())}finally{setRefreshing(false)}},[]);useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),12000);return()=>clearInterval(id)},[refresh]);const items=home?.items||[];return <ScrollView style={{flex:1,backgroundColor:t.paper}} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void refresh()}}/>} contentContainerStyle={[s.wrap,{paddingTop:i.top+22,paddingBottom:96+i.bottom}]}><View style={s.heading}><View><Text style={[s.title,{color:t.ink}]}>Today</Text><Text style={[s.date,{color:t.ink3}]}>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</Text></View><Gogo state={stateForHome(home?.state)} size={48}/></View>{items.length?items.map(x=><TodayRow key={x.id} item={x}/>):<View style={s.empty}><Gogo state="calm" size={56}/><Text style={[s.emptyTitle,{color:t.ink}]}>All quiet for now.</Text><Text style={[s.emptyBody,{color:t.ink2}]}>Gogo will put meaningful updates here as your day changes.</Text></View>}</ScrollView>}
function TodayRow({item}:{item:AgentHomeItem}){const t=useTheme();const accent=item.kind==='watching'?'#5B8DD6':item.kind==='done'?'#3DB283':'#F26B1D';return <View style={[s.row,{borderBottomColor:t.rowLine}]}><View style={s.char}><Gogo state={stateForItem(item.kind)} size={34}/></View><View style={{flex:1}}><View style={s.metaRow}><Text style={[s.meta,{color:accent}]}>{item.kind==='approval'?'Needs you':item.kind==='watching'?'Watching':item.kind==='done'?'Done':item.kind==='idea'?'Found':'Working'}</Text>{item.timestamp?<Text style={[s.time,{color:t.ink3}]}>{new Date(item.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text>:null}</View><Text style={[s.itemTitle,{color:t.ink}]}>{item.title}</Text><Text style={[s.body,{color:t.ink2}]}>{item.body}</Text>{item.actionLabel?<Text style={s.action}>{item.actionLabel} ›</Text>:null}</View></View>}
const s=StyleSheet.create({wrap:{paddingHorizontal:20},heading:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},title:{fontSize:32,fontWeight:'700',letterSpacing:-.8},date:{fontSize:12,marginTop:4,marginBottom:18},row:{flexDirection:'row',gap:10,paddingVertical:15,borderBottomWidth:StyleSheet.hairlineWidth},char:{width:36,paddingTop:1},metaRow:{flexDirection:'row',justifyContent:'space-between'},meta:{fontSize:9,fontWeight:'800',letterSpacing:.5},time:{fontSize:9},itemTitle:{fontSize:15,fontWeight:'700',marginTop:5},body:{fontSize:12,lineHeight:17,marginTop:4},action:{fontSize:11,fontWeight:'700',color:'#F26B1D',marginTop:8},empty:{paddingTop:54},emptyTitle:{fontSize:20,fontWeight:'700',marginTop:12},emptyBody:{fontSize:14,lineHeight:20,marginTop:7,maxWidth:300}})
