import type { AgentHomeSnapshot } from './types'

export const agentPreview: AgentHomeSnapshot = {
  runs: [
    {
      id: 'run-flight-watch',
      title: 'Watching BLR → Dubai fares',
      summary: 'Tell me when a good nonstop option drops below ₹25,000.',
      status: 'watching',
      capability: 'travel',
      progress: 62,
      startedAt: '2026-09-09T02:00:00Z',
      updatedAt: '2026-09-09T02:35:00Z',
      nextCheckAt: '2026-09-09T03:35:00Z',
      why: 'You asked Gogo to watch instead of repeatedly searching yourself.',
    },
    {
      id: 'run-accelerator',
      title: 'Preparing accelerator application',
      summary: 'Founder profile and company context are ready. Submission needs your approval.',
      status: 'waiting_approval',
      capability: 'browser',
      progress: 88,
      startedAt: '2026-09-09T01:15:00Z',
      updatedAt: '2026-09-09T02:31:00Z',
      why: 'This action submits information externally, so Gogo will never silently submit it.',
    },
    {
      id: 'run-email-followup',
      title: 'Waiting for an investor reply',
      summary: 'Gogo will surface it when the thread changes or the follow-up date arrives.',
      status: 'watching',
      capability: 'email',
      startedAt: '2026-09-08T10:00:00Z',
      updatedAt: '2026-09-09T02:20:00Z',
      why: 'The thread is connected to an active fundraising goal.',
    },
  ],
  goals: [
    {
      id: 'goal-creditiq-uae',
      title: 'Launch CreditIQ UAE',
      outcome: 'Investor-ready UAE launch with first accelerator and partner pipeline active.',
      status: 'active',
      progress: 62,
      deadline: '2026-10-31',
      nextAction: 'Finish UAE accelerator submission',
      watchers: 3,
      blockers: ['One application requires final founder approval'],
    },
    {
      id: 'goal-ny-trip',
      title: 'New York trip ready',
      outcome: 'Meetings, hotel, watch purchase and departure checklist complete before travel.',
      status: 'active',
      progress: 41,
      deadline: '2026-09-28',
      nextAction: 'Book hotel after shortlist approval',
      watchers: 2,
    },
  ],
  ideas: [
    {
      id: 'idea-watch',
      title: 'Check the watch before you land in New York',
      reason: 'You saved a Christopher Ward watch and your New York trip is approaching.',
      expectedValue: 'Avoid a wasted store visit or late delivery.',
      status: 'new',
      actionLabel: 'Watch availability',
      sourceLabel: 'Memory + travel',
    },
    {
      id: 'idea-deadline',
      title: 'Prepare accelerator answers before the Dubai travel window',
      reason: 'A tracked application deadline overlaps your travel schedule.',
      expectedValue: 'Submit calmly before travel instead of chasing it at the deadline.',
      status: 'new',
      actionLabel: 'Prepare draft',
      sourceLabel: 'Goal + calendar',
    },
    {
      id: 'idea-creditiq',
      title: 'Use CreditIQ before paying for the next flight',
      reason: 'Your travel goal contains a cash booking and multiple premium-card options.',
      expectedValue: 'Compare effective reward value before checkout.',
      status: 'new',
      actionLabel: 'Compare cards',
      sourceLabel: 'CreditIQ + travel',
    },
  ],
  approvals: [
    {
      id: 'approval-accelerator-submit',
      runId: 'run-accelerator',
      actionType: 'submit_form',
      title: 'Ready to submit accelerator application',
      description: 'Gogo has prepared the form. Review the external submission before it leaves AskGogo.',
      risk: 'high',
      status: 'pending',
      primaryLabel: 'Review & approve',
      secondaryLabel: 'Keep as draft',
      preview: [
        { label: 'Company', value: 'CreditIQ' },
        { label: 'Founder', value: 'Goverdhan M D' },
        { label: 'Action', value: 'Submit external application form' },
      ],
    },
  ],
  permissions: [
    { capability: 'memory', label: 'Memory', description: 'Use your AskGogo memory when relevant.', level: 'read', irreversibleAlwaysAsk: false },
    { capability: 'files', label: 'Files', description: 'Read connected files and prepare summaries/drafts.', level: 'read', irreversibleAlwaysAsk: false },
    { capability: 'email', label: 'Email', description: 'Read and draft. Sending requires approval.', level: 'draft', irreversibleAlwaysAsk: true },
    { capability: 'calendar', label: 'Calendar', description: 'Read and prepare changes. Destructive changes always ask.', level: 'ask', irreversibleAlwaysAsk: true },
    { capability: 'browser', label: 'Browser', description: 'Research and fill drafts. Submit actions always ask.', level: 'draft', irreversibleAlwaysAsk: true },
    { capability: 'travel', label: 'Travel', description: 'Research, compare and watch fares or availability.', level: 'draft', irreversibleAlwaysAsk: true },
    { capability: 'contacts', label: 'Contacts', description: 'Resolve people for reminders, email and calendar.', level: 'read', irreversibleAlwaysAsk: false },
    { capability: 'payments', label: 'Payments', description: 'Never pay or purchase without explicit approval.', level: 'ask', irreversibleAlwaysAsk: true },
  ],
  artifacts: [
    { id: 'artifact-uae', type: 'application_tracker', title: 'UAE accelerator tracker', subtitle: '4 applications · 2 need action', updatedAt: '2026-09-09T02:30:00Z' },
    { id: 'artifact-ny', type: 'trip', title: 'New York trip', subtitle: 'Meetings · hotel · shopping · checklist', updatedAt: '2026-09-09T02:25:00Z' },
  ],
}
