import { useEffect, useMemo, useState } from 'react'
import { Linking, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import * as Notifications from 'expo-notifications'
import { agentApi } from '../src/agent/api'
import type { AgentHomeSnapshot, AgentPermission } from '../src/agent/types'
import { clearMobileSession } from '../src/auth/session'
import { Gogo } from '../src/design/Gogo'
import { useTheme } from '../src/theme'

type Section='notifications'|'permissions'|'devices'|'privacy'|'account'|'whatsapp'|'appearance'
const TITLES:Record<Section,string>={notifications:'Notifications',permissions:'Permissions',devices:'Connected devices',privacy:'Privacy',account:'Account',whatsapp:'WhatsApp',appearance:'Appearance'}

export default function Settings(){
  const t=useTheme(), r=useRouter(), i=useSafeAreaInsets(); const p=useLocalSearchParams<{section?:string}>()
  const section=(p.section||'account') as Section
  const [snap,setSnap]=useState<AgentHomeSnapshot|null>(null); const [notice,setNotice]=useState(''); const [notif,setNotif]=useState('Checking…')
  useEffect(()=>{void agentApi.snapshot().then(setSnap).catch(()=>{}); if(section==='notifications')void Notifications.getPermissionsAsync().then(x=>setNotif(x.status))},[section])
  async function requestNotifications(){const x=await Notifications.requestPermissionsAsync();setNotif(x.status);setNotice(x.status==='granted'?'Notifications are enabled.':'Notification permission was not granted.')}
  async function signOut(){await clearMobileSession();r.replace('/connect')}
  return <ScrollView style={{flex:1,backgroundColor:t.paper}} contentContainerStyle={[s.wrap,{paddingTop:i.top+12,paddingBottom:30+i.bottom}]}>
    <View style={s.header}><Pressable onPress={()=>r.back()} style={[s.back,{backgroundColor:t.surface}]}><Ionicons name="chevron-back" size={24} color={t.ink}/></Pressable><View style={{flex:1}}><Text style={[s.title,{color:t.ink}]}>{TITLES[section]||'Settings'}</Text><Text style={[s.sub,{color:t.ink3}]}>AskGogo settings</Text></View><Gogo state={section==='privacy'?'secure':'calm'} size={48}/></View>
    {section==='notifications'?<><Card><Text style={[s.cardTitle,{color:t.ink}]}>Permission: {notif}</Text><Text style={[s.body,{color:t.ink2}]}>AskGogo uses notifications for approvals, reminders and meaningful watcher updates.</Text><Primary onPress={requestNotifications} text={notif==='granted'?'Refresh permission':'Enable notifications'}/></Card><ActionRow icon="settings-outline" title="Open Android notification settings" onPress={()=>Linking.openSettings()}/></>:null}
    {section==='permissions'?<Permissions snap={snap} onSnap={setSnap}/>:null}
    {section==='devices'?<><Card><Text style={[s.cardTitle,{color:t.ink}]}>This phone</Text><Text style={[s.body,{color:t.ink2}]}>Connected with its own revocable AskGogo mobile session.</Text></Card><ActionRow icon="desktop-outline" title="Open web Agent Hub" onPress={()=>Linking.openURL('https://app.askgogo.in/dashboard/agent')}/><ActionRow icon="settings-outline" title="Open device settings" onPress={()=>Linking.openSettings()}/></>:null}
    {section==='privacy'?<><Card><Text style={[s.cardTitle,{color:t.ink}]}>Same brain, controlled access</Text><Text style={[s.body,{color:t.ink2}]}>Your mobile app stores an opaque device session. Secure actions still follow AskGogo approval and permission gates.</Text></Card><ActionRow icon="library-outline" title="Review Memory" onPress={()=>r.replace('/(tabs)/memory')}/><ActionRow icon="key-outline" title="Review permissions" onPress={()=>r.setParams({section:'permissions'})}/></>:null}
    {section==='whatsapp'?<><Card><Text style={[s.cardTitle,{color:t.ink}]}>WhatsApp connected</Text><Text style={[s.body,{color:t.ink2}]}>This app uses the same AskGogo identity as WhatsApp. Your WhatsApp password never enters the app.</Text></Card><ActionRow icon="logo-whatsapp" title="Re-link WhatsApp identity" onPress={()=>r.replace('/connect')}/></>:null}
    {section==='appearance'?<><Card><Text style={[s.cardTitle,{color:t.ink}]}>Light</Text><Text style={[s.body,{color:t.ink2}]}>The Claude redesign uses Light as the default AskGogo appearance. Dark/System can be added as an explicit preference without changing the design default.</Text></Card></>:null}
    {section==='account'?<><Card><Text style={[s.cardTitle,{color:t.ink}]}>AskGogo 2.0</Text><Text style={[s.body,{color:t.ink2}]}>One identity across WhatsApp, mobile and the web dashboard.</Text></Card><ActionRow icon="desktop-outline" title="Open web dashboard" onPress={()=>Linking.openURL('https://app.askgogo.in/dashboard/agent')}/><Pressable onPress={signOut} style={s.signOut}><Text style={s.signOutText}>Sign out on this phone</Text></Pressable></>:null}
    {!!notice?<Text style={s.notice}>{notice}</Text>:null}
  </ScrollView>
}

function Permissions({snap,onSnap}:{snap:AgentHomeSnapshot|null;onSnap:(s:AgentHomeSnapshot)=>void}){const t=useTheme();const permissions=snap?.permissions||[];async function set(p:AgentPermission,level:AgentPermission['level']){const changed=await agentApi.updatePermission(p.capability,level);if(snap)onSnap({...snap,permissions:snap.permissions.map(x=>x.capability===changed.capability?changed:x)})}return <>{permissions.length?permissions.map(p=><View key={p.capability} style={[s.permission,{borderBottomColor:t.rowLine}]}><View style={{flex:1}}><Text style={[s.permissionTitle,{color:t.ink}]}>{p.label}</Text><Text style={[s.permissionBody,{color:t.ink3}]}>{p.description}</Text>{p.irreversibleAlwaysAsk?<Text style={s.alwaysAsk}>Irreversible actions always ask</Text>:null}</View><View style={s.pills}>{(['off','read','draft','ask','auto'] as const).map(level=><Pressable key={level} onPress={()=>set(p,level)} style={[s.pill,{backgroundColor:p.level===level?'#F26B1D':t.surface}]}><Text style={[s.pillText,{color:p.level===level?'#fff':t.ink2}]}>{level}</Text></Pressable>)}</View></View>):<Text style={[s.body,{color:t.ink2}]}>Loading AskGogo permissions…</Text>}<ActionRow icon="settings-outline" title="Android app permissions" onPress={()=>Linking.openSettings()}/></>}
function Card({children}:{children:React.ReactNode}){const t=useTheme();return <View style={[s.card,{backgroundColor:t.surface}]}>{children}</View>}
function Primary({text,onPress}:{text:string;onPress:()=>void}){return <Pressable onPress={onPress} style={s.primary}><Text style={s.primaryText}>{text}</Text></Pressable>}
function ActionRow({icon,title,onPress}:{icon:keyof typeof Ionicons.glyphMap;title:string;onPress:()=>void}){const t=useTheme();return <Pressable onPress={onPress} style={[s.actionRow,{borderBottomColor:t.rowLine}]}><Ionicons name={icon} size={20} color={t.ink2}/><Text style={[s.actionText,{color:t.ink}]}>{title}</Text><Ionicons name="chevron-forward" size={18} color={t.ink3}/></Pressable>}
const s=StyleSheet.create({wrap:{paddingHorizontal:20},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:28},back:{width:44,height:44,borderRadius:16,alignItems:'center',justifyContent:'center'},title:{fontSize:28,fontWeight:'700'},sub:{fontSize:11,marginTop:2},card:{borderRadius:18,padding:18,marginBottom:18},cardTitle:{fontSize:18,fontWeight:'700'},body:{fontSize:13,lineHeight:19,marginTop:6},primary:{height:46,borderRadius:16,backgroundColor:'#F26B1D',alignItems:'center',justifyContent:'center',marginTop:16},primaryText:{color:'#fff',fontWeight:'800'},actionRow:{minHeight:64,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center',gap:12},actionText:{flex:1,fontSize:15,fontWeight:'600'},permission:{paddingVertical:16,borderBottomWidth:StyleSheet.hairlineWidth},permissionTitle:{fontSize:15,fontWeight:'700'},permissionBody:{fontSize:11,lineHeight:16,marginTop:3},alwaysAsk:{fontSize:10,color:'#F26B1D',marginTop:5,fontWeight:'700'},pills:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:10},pill:{borderRadius:999,paddingHorizontal:9,paddingVertical:6},pillText:{fontSize:10,fontWeight:'700',textTransform:'capitalize'},signOut:{height:50,borderRadius:16,borderWidth:1,borderColor:'#E1DCD6',alignItems:'center',justifyContent:'center',marginTop:24},signOutText:{color:'#B34B3E',fontWeight:'700'},notice:{fontSize:12,color:'#3DB283',marginTop:16}})
