import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { useRouter } from 'expo-router'
import { agentApi } from '../src/agent/api'
import type { AgentArtifact, AgentArtifactDetail, AgentThread } from '../src/agent/types'

const C={bg:'#F6F0E8',paper:'#FFFDF9',ink:'#3A2418',muted:'#8C7769',line:'#E6DBD2',orange:'#F47B20',dark:'#3A2519',lav:'#F0EDFF',mint:'#EAF8EF',blue:'#EDF7FF'}

export default function Workspaces(){
  const router=useRouter();const [threads,setThreads]=useState<AgentThread[]>([]);const [artifacts,setArtifacts]=useState<AgentArtifact[]>([]);const [title,setTitle]=useState('');const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [detail,setDetail]=useState<AgentArtifactDetail|null>(null)
  async function load(){try{const [t,s]=await Promise.all([agentApi.threads(),agentApi.snapshot()]);setThreads(t);setArtifacts(s.artifacts||[]);setError('')}catch(e:any){setError(e?.message||'Could not load workspaces.')}finally{setBusy(false)}}
  useEffect(()=>{load()},[])
  async function create(){const v=title.trim();if(!v)return;setBusy(true);try{await agentApi.createThread(v);setTitle('');await load()}catch(e:any){setError(e?.message||'Could not create workspace.');setBusy(false)}}
  async function openArtifact(a:AgentArtifact){setBusy(true);try{setDetail(await agentApi.artifact(a.id));setError('')}catch(e:any){setError(e?.message||'Could not open artifact.')}finally{setBusy(false)}}
  if(busy&&!threads.length&&!artifacts.length)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={C.orange}/><Text style={s.muted}>Opening your Gogo workspaces…</Text></View></SafeAreaView>
  return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.icon}><Ionicons name="chevron-back" size={19} color={C.ink}/></Pressable><View style={{flex:1}}><Text style={s.title}>Gogo Workspaces</Text><Text style={s.sub}>Separate projects · one shared Memory</Text></View></View><ScrollView contentContainerStyle={s.content}>
    <Text style={s.kicker}>PARALLEL WORK</Text><Text style={s.hero}>Give big outcomes their own space.</Text><Text style={s.body}>A workspace keeps one trip, raise, application or project focused while still using the same AskGogo memory and permissions.</Text>
    <Pressable onPress={()=>router.push('/capture' as never)} style={s.capture}><View style={[s.box,{backgroundColor:C.blue}]}><Ionicons name="sparkles" size={19} color="#4775A8"/></View><View style={{flex:1}}><Text style={s.cardTitle}>Capture & Share</Text><Text style={s.cardText}>Voice commands · scan documents · PDFs/files · Android & iOS share sheet</Text></View><Ionicons name="chevron-forward" size={17} color={C.muted}/></Pressable>
    <View style={s.create}><TextInput value={title} onChangeText={setTitle} placeholder="e.g. CreditIQ Seed Raise" style={s.input}/><Pressable onPress={create} disabled={!title.trim()||busy} style={s.add}><Ionicons name="add" size={20} color="white"/></Pressable></View>
    {!!error&&<Text style={s.error}>{error}</Text>}
    <Section t="Workspaces" r={`${threads.length}`}/>{!threads.length&&<Empty t="No workspaces yet" d="Create one above for a focused side chat/project."/>}{threads.map(t=><Pressable key={t.id} onPress={()=>router.push({pathname:'/agent',params:{threadId:t.id,threadTitle:t.title}})} style={s.card}><View style={[s.box,{backgroundColor:C.lav}]}><Ionicons name="layers-outline" size={18} color="#6658B5"/></View><View style={{flex:1}}><Text style={s.cardTitle}>{t.title}</Text><Text style={s.cardText}>Open with Gogo · shared Memory</Text></View><Ionicons name="chevron-forward" size={17} color={C.muted}/></Pressable>)}
    <Section t="Artifacts" r={`${artifacts.length}`}/>{!artifacts.length&&<Empty t="No artifacts yet" d="Research briefs, goal trackers and trip workspaces created by Gogo will appear here."/>}{artifacts.map(a=><Pressable key={a.id} onPress={()=>openArtifact(a)} style={s.card}><View style={[s.box,{backgroundColor:C.mint}]}><Ionicons name="document-text-outline" size={18} color="#39815D"/></View><View style={{flex:1}}><Text style={s.cardTitle}>{a.title}</Text><Text style={s.cardText}>{a.subtitle||a.type.replaceAll('_',' ')}</Text></View><Ionicons name="open-outline" size={16} color={C.muted}/></Pressable>)}
    {detail&&<View style={s.detail}><View style={s.detailHead}><View style={{flex:1}}><Text style={s.kicker}>{detail.type.replaceAll('_',' ').toUpperCase()}</Text><Text style={s.detailTitle}>{detail.title}</Text></View><Pressable onPress={()=>setDetail(null)}><Ionicons name="close" size={20} color={C.ink}/></Pressable></View><Text style={s.detailText}>{pretty(detail.content)}</Text><Text style={s.source}>Private AskGogo artifact · updated {new Date(detail.updatedAt).toLocaleString()}</Text></View>}
  </ScrollView></SafeAreaView>
}
function pretty(v:Record<string,unknown>){try{return JSON.stringify(v,null,2).slice(0,12000)}catch{return 'Artifact content could not be displayed.'}}
function Section({t,r}:{t:string;r:string}){return <View style={s.section}><Text style={s.sectionTitle}>{t}</Text><Text style={s.sectionRight}>{r}</Text></View>}
function Empty({t,d}:{t:string;d:string}){return <View style={s.empty}><Text style={s.cardTitle}>{t}</Text><Text style={s.cardText}>{d}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},muted:{fontSize:11,color:C.muted},header:{height:68,paddingHorizontal:15,flexDirection:'row',gap:10,alignItems:'center',borderBottomWidth:1,borderBottomColor:C.line},icon:{width:38,height:38,borderRadius:15,backgroundColor:C.paper,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line},title:{fontFamily:'serif',fontSize:20,fontWeight:'700',color:C.ink},sub:{fontSize:8.5,color:C.muted},content:{padding:17,paddingBottom:60},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:C.orange},hero:{fontFamily:'serif',fontSize:29,lineHeight:33,fontWeight:'700',color:C.ink,marginTop:8},body:{fontSize:11,lineHeight:17,color:C.muted,marginTop:8},capture:{marginTop:16,borderRadius:20,borderWidth:1,borderColor:'#D9E7F3',backgroundColor:'#F7FBFF',padding:13,flexDirection:'row',gap:10,alignItems:'center'},create:{marginTop:12,flexDirection:'row',gap:8},input:{flex:1,height:50,borderRadius:16,borderWidth:1,borderColor:C.line,backgroundColor:C.paper,paddingHorizontal:14,color:C.ink},add:{width:50,height:50,borderRadius:16,backgroundColor:C.orange,alignItems:'center',justifyContent:'center'},error:{fontSize:10,color:'#A43B2E',marginTop:10},section:{marginTop:24,marginBottom:9,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},sectionTitle:{fontFamily:'serif',fontSize:20,fontWeight:'700',color:C.ink},sectionRight:{fontSize:9,color:C.muted},card:{borderRadius:19,borderWidth:1,borderColor:C.line,backgroundColor:C.paper,padding:12,marginBottom:8,flexDirection:'row',gap:10,alignItems:'center'},box:{width:40,height:40,borderRadius:13,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:11,fontWeight:'800',color:C.ink},cardText:{fontSize:9,lineHeight:14,color:C.muted,marginTop:2},empty:{padding:14,borderRadius:18,borderWidth:1,borderColor:C.line,backgroundColor:C.paper},detail:{marginTop:22,padding:16,borderRadius:22,backgroundColor:C.dark},detailHead:{flexDirection:'row',alignItems:'flex-start'},detailTitle:{fontFamily:'serif',fontSize:22,fontWeight:'700',color:'white',marginTop:5},detailText:{fontFamily:'monospace',fontSize:9,lineHeight:14,color:'#E7DCD4',marginTop:14},source:{fontSize:8,color:'#BDAEA4',marginTop:14}})
