export type GogoLesson = {
  key: string
  title: string
  minutes: number
  category: string
  description: string
  prompt?: string
  videoSrc?: string
  audioSrc?: string
  example?: string
  result?: string
  tryText?: string
  steps?: string[]
}

export const GOGO_LESSONS: GogoLesson[] = [
  {
    key: 'meet-gogo',
    title: 'Meet Gogo',
    minutes: 1,
    category: 'Start here',
    description: 'Meet the calm second brain that lives with you on WhatsApp and the web.',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/0e7ef01f-fbf6-48fc-98ab-6ba94f4539bd.mp3',
    example: 'Tell Gogo what you need — reminders, memory, lists, documents, meetings, travel and more.',
    result: 'One Gogo. Same memory. WhatsApp + dashboard.',
    tryText: 'Finish this short introduction to unlock your first real skill.',
    steps: ['Talk naturally.', 'Gogo remembers useful context.', 'Your WhatsApp and dashboard stay in sync.'],
  },
  {
    key: 'first-reminder',
    title: 'Your first reminder',
    minutes: 1,
    category: 'Reminders',
    description: 'Say it naturally. Gogo turns a sentence into something you no longer need to hold in your head.',
    prompt: 'Remind me tomorrow at 10 AM to call Mom',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/cac41bed-d44b-44b3-8708-234f8cb6bffa.mp3',
    example: 'Remind me tomorrow at 10 AM to call Mom',
    result: '✓ Reminder set · Call Mom · Tomorrow 10:00 AM',
    tryText: 'Create one reminder you actually need.',
    steps: ['Tell Gogo what and when.', 'Gogo confirms the interpreted time.', 'Reply naturally if you want to move, snooze or change it.'],
  },
  {
    key: 'save-something',
    title: "Save something you don't want to lose",
    minutes: 1,
    category: 'Memory',
    description: 'Give Gogo an image, screenshot, PDF or useful document and keep the original with the context that makes it useful later.',
    prompt: 'Save this',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/69635c40-98ae-47ad-82dd-531d34fdf456.mp3',
    example: 'Save this',
    result: '✓ Saved privately with useful context and the original file.',
    tryText: 'Save one real image, screenshot, PDF or document.',
    steps: ['Say save this, then send the image or document — or send it first and say save this.', 'Gogo files the original privately with useful context.', 'Sensitive documents stay masked by default.'],
  },
  {
    key: 'find-it-again',
    title: 'Find it again',
    minutes: 1,
    category: 'Memory',
    description: 'Experience the magic of asking naturally for something you saved without remembering a filename or folder.',
    prompt: 'Show me what I saved about Jopasu',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/0984379c-a0db-412e-ab9e-edae841e2a29.mp3',
    example: 'Show me what I saved about Jopasu',
    result: 'Gogo finds the closest saved item and gives you the original when appropriate.',
    tryText: 'Retrieve the item you saved in the previous lesson.',
    steps: ['Ask using the person, brand, amount or phrase you remember.', 'Gogo ranks the most likely saved item.', 'Open the original when you need the source file.'],
  },
  {
    key: 'voice-notes',
    title: 'Use your voice',
    minutes: 1,
    category: 'Capture',
    description: 'Send a voice note when typing is inconvenient. Gogo can turn speech into actions and notes.',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/fbd53bbc-6a2c-4c8c-a26f-0c86da5a5ae8.mp3',
    example: '🎙 “Remind me at 6 PM to call Srinivas.”',
    result: 'Gogo understands the voice note and turns it into the right action.',
    tryText: 'Send Gogo one useful voice note on WhatsApp.',
    steps: ['Open AskGogo on WhatsApp.', 'Hold the microphone and speak naturally.', 'For meetings, say meeting notes or use the recorder.'],
  },
  {
    key: 'recurring-reminders',
    title: 'Recurring reminders',
    minutes: 1,
    category: 'Reminders',
    description: 'Daily, weekly and repeating routines without rebuilding the reminder each time.',
    prompt: 'Remind me every day at 6 PM to drink water',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/84c14e84-3820-4bfc-9415-864019925898.mp3',
    example: 'Remind me every Monday at 9 AM to send the weekly report',
    result: '↻ Recurring reminder · Every Monday · 9:00 AM',
    tryText: 'Create one recurring reminder.',
    steps: ['Use everyday language such as every day or every Monday.', 'Gogo keeps the recurrence with the reminder.', 'You can change or resolve an occurrence later.'],
  },
  {
    key: 'lists-tasks',
    title: 'Lists and tasks',
    minutes: 1,
    category: 'Organize',
    description: 'Build grocery lists, project lists and tasks, then check things off from WhatsApp or the dashboard.',
    prompt: 'Add milk to my grocery list',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/8b4ad900-3414-48fd-853b-38c19994cca7.mp3',
    example: 'Add milk to my grocery list',
    result: '✓ Milk added to Grocery list',
    tryText: 'Add one real item to a list.',
    steps: ['Name the item and list.', 'Ask to show the list any time.', 'Say done plus an item name to clear it.'],
  },
  {
    key: 'screenshots-links',
    title: 'Screenshots and useful links',
    minutes: 1,
    category: 'Memory',
    description: 'Keep useful visual references and links without losing them inside old chats.',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/8f1c5081-b52e-43f1-bd2a-3ab3de96cf03.mp3',
    example: 'Send a screenshot or useful link and tell Gogo why it matters.',
    result: 'Gogo keeps the reference with enough context to find it later.',
    tryText: 'Send one screenshot or useful link you want to keep.',
    steps: ['Send the screenshot or link.', 'Tell Gogo what it means if the context is not obvious.', 'Search for it later by the words you remember.'],
  },
  {
    key: 'calendar',
    title: 'Connect your calendar',
    minutes: 1,
    category: 'Calendar',
    description: 'Bring Google Calendar into Today and let Gogo help around your real schedule.',
    prompt: 'Connect calendar',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/050ef327-ca85-4326-8440-9bb5d2ebeecc.mp3',
    example: 'Connect calendar',
    result: 'Calendar connected · events can appear beside reminders in Today.',
    tryText: 'Connect Google Calendar if you have not already.',
    steps: ['Connect Google Calendar once.', 'Your day can include real events alongside reminders.', 'Ask Gogo to create or move calendar events naturally.'],
  },
  {
    key: 'plan-your-day',
    title: 'Plan your day',
    minutes: 1,
    category: 'Planning',
    description: 'Bring meetings, reminders and priorities together so Gogo can help you see what matters now.',
    prompt: 'Plan my day',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/f845ab88-d1d4-4958-9213-fffc466c3c7e.mp3',
    example: 'Plan my day',
    result: 'Gogo brings together the important meetings, reminders and priorities.',
    tryText: 'Ask Gogo to plan your real day.',
    steps: ['Ask Gogo to plan your day.', 'Review the important events and reminders together.', 'Turn anything missing into a reminder or task.'],
  },
  {
    key: 'daily-brief',
    title: 'Daily Brief',
    minutes: 1,
    category: 'Planning',
    description: 'Wake up to the day already organized — weather, calendar, reminders and travel when relevant.',
    prompt: 'Today',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/2e381267-85e8-401a-b123-98df2fed276a.mp3',
    example: 'Good morning · Weather · Calendar · Reminders · Travel when relevant',
    result: 'Your day arrives already organized in one calm brief.',
    tryText: 'Open Today and review your Daily Brief settings.',
    steps: ['Choose your briefing time.', 'Keep WhatsApp briefing and email briefing independently on or off.', 'Use Today to turn the important parts into actions.'],
  },
  {
    key: 'meeting-recorder',
    title: 'Meetings with Gogo',
    minutes: 2,
    category: 'Meetings',
    description: 'Record a meeting, get the transcript, decisions and follow-ups, then turn actions into reminders.',
    prompt: 'Record meeting',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/f98d7123-5df8-46ec-9394-be3af39cf4db.mp3',
    example: 'Record meeting',
    result: 'Transcript · Decisions · Action items · Follow-up reminders',
    tryText: 'Try the meeting recorder with a short real conversation.',
    steps: ['Start the AskGogo recorder from WhatsApp.', 'End the recording when the meeting is finished.', 'Review transcript, decisions and action items back in AskGogo.'],
  },
  {
    key: 'travel',
    title: 'Travel with Gogo',
    minutes: 1,
    category: 'Travel',
    description: 'Send a ticket or itinerary and let Gogo keep the travel details and timing close at hand.',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/a80d089a-2bcb-4148-84d8-dc70dab465f4.mp3',
    example: 'Send a flight ticket or itinerary to Gogo.',
    result: 'Flight · route · date · timing · useful travel reminders',
    tryText: 'Send one real ticket or itinerary when you have one.',
    steps: ['Send a ticket image or PDF.', 'Gogo extracts useful travel details.', 'Use Today and reminders around departure and check-in.'],
  },
  {
    key: 'personalize-gogo',
    title: 'Personalize Gogo',
    minutes: 1,
    category: 'Your Gogo',
    description: 'Choose how Gogo speaks to you and the small touches that make your calm space feel like yours.',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/d0284788-6d17-4932-bf38-3e88a07628ce.mp3',
    example: 'Calm companion · Sharp professional · Straight-talking coach · Quiet minimalist',
    result: 'Same truth and memory — a tone and space that feel more like yours.',
    tryText: 'Open Personalize Gogo and save your preferred style.',
    steps: ['Open Personalize Gogo.', 'Choose the personality that feels right.', 'Pick the comfort drink beside Gogo and save your Gogo.'],
  },
  {
    key: 'breathing',
    title: 'Breathe with Gogo',
    minutes: 1,
    category: 'Calm',
    description: 'Three breathing patterns with original ambient sound for a short reset inside the dashboard.',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/59ad49c0-e4e1-4dd5-8add-7c7e159fb0f7.mp3',
    example: 'Balance · Stress Reset · Deep Relax',
    result: 'A short guided reset without leaving your calm space.',
    tryText: 'Complete one breathing cycle with Gogo.',
    steps: ['Tap the meditating Gogo button.', 'Choose Balance, Stress Reset or Deep Relax.', 'Turn sound on if you want the generated soundscape.'],
  },
  {
    key: 'memory-search',
    title: 'Search your second brain',
    minutes: 1,
    category: 'Memory',
    description: 'Search across what Gogo has learned and saved using the way you naturally remember it.',
    prompt: 'What do you remember about my saved documents?',
    audioSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/0fe64342-09c6-450f-ac62-eacd7c297ab4.mp3',
    example: 'What do you remember about my saved documents?',
    result: 'Ask by names, brands, dates, amounts or phrases — not folders.',
    tryText: 'Ask one natural question about something Gogo already knows.',
    steps: ['Ask naturally instead of browsing folders.', 'Use names, brands, dates, amounts or phrases as clues.', 'Open the relevant memory or original source when you need it.'],
  },
]
