export type GogoLesson = {
  key: string
  title: string
  minutes: number
  category: string
  description: string
  prompt?: string
  videoSrc?: string
  steps?: string[]
}

export const GOGO_LESSONS: GogoLesson[] = [
  {
    key: 'meet-gogo',
    title: 'Meet Gogo',
    minutes: 1,
    category: 'Start here',
    description: 'A quick overview of the second brain that lives with you on WhatsApp and the web.',
    videoSrc: '/askgogo_demo.mp4',
  },
  {
    key: 'first-reminder',
    title: 'Your first reminder',
    minutes: 1,
    category: 'Reminders',
    description: 'Say it naturally. Gogo turns a sentence into something you no longer need to hold in your head.',
    prompt: 'Remind me tomorrow at 10 AM to call Mom',
    steps: ['Tell Gogo what and when.', 'Gogo confirms the interpreted time.', 'Reply naturally if you want to move, snooze or change it.'],
  },
  {
    key: 'save-something',
    title: "Save something you don't want to lose",
    minutes: 1,
    category: 'Memory',
    description: 'Give Gogo an image, screenshot, PDF or useful document and keep the original with the context that makes it useful later.',
    prompt: 'Save this',
    steps: ['Say save this, then send the image or document — or send it first and say save this.', 'Gogo files the original privately with useful context.', 'Sensitive documents stay masked by default.'],
  },
  {
    key: 'find-it-again',
    title: 'Find it again',
    minutes: 1,
    category: 'Memory',
    description: 'Experience the magic of asking naturally for something you saved without remembering a filename or folder.',
    prompt: 'Show me what I saved about Jopasu',
    steps: ['Ask using the person, brand, amount or phrase you remember.', 'Gogo ranks the most likely saved item.', 'Open the original when you need the source file.'],
  },
  {
    key: 'voice-notes',
    title: 'Use your voice',
    minutes: 1,
    category: 'Capture',
    description: 'Send a voice note when typing is inconvenient. Gogo can turn speech into actions and notes.',
    steps: ['Open AskGogo on WhatsApp.', 'Hold the microphone and speak naturally.', 'For meetings, say meeting notes or use the recorder.'],
  },
  {
    key: 'recurring-reminders',
    title: 'Recurring reminders',
    minutes: 1,
    category: 'Reminders',
    description: 'Daily, weekly and repeating routines without rebuilding the reminder each time.',
    prompt: 'Remind me every day at 6 PM to drink water',
    steps: ['Use everyday language such as every day or every Monday.', 'Gogo keeps the recurrence with the reminder.', 'You can change or resolve an occurrence later.'],
  },
  {
    key: 'lists-tasks',
    title: 'Lists and tasks',
    minutes: 1,
    category: 'Organize',
    description: 'Build grocery lists, project lists and tasks, then check things off from WhatsApp or the dashboard.',
    prompt: 'Add milk to my grocery list',
    steps: ['Name the item and list.', 'Ask to show the list any time.', 'Say done plus an item name to clear it.'],
  },
  {
    key: 'screenshots-links',
    title: 'Screenshots and useful links',
    minutes: 1,
    category: 'Memory',
    description: 'Keep useful visual references and links without losing them inside old chats.',
    steps: ['Send the screenshot or link.', 'Tell Gogo what it means if the context is not obvious.', 'Search for it later by the words you remember.'],
  },
  {
    key: 'calendar',
    title: 'Connect your calendar',
    minutes: 1,
    category: 'Calendar',
    description: 'Bring Google Calendar into Today and let Gogo help around your real schedule.',
    prompt: 'Connect calendar',
    steps: ['Connect Google Calendar once.', 'Your day can include real events alongside reminders.', 'Ask Gogo to create or move calendar events naturally.'],
  },
  {
    key: 'plan-your-day',
    title: 'Plan your day',
    minutes: 1,
    category: 'Planning',
    description: 'Bring meetings, reminders and priorities together so Gogo can help you see what matters now.',
    prompt: 'Plan my day',
    steps: ['Ask Gogo to plan your day.', 'Review the important events and reminders together.', 'Turn anything missing into a reminder or task.'],
  },
  {
    key: 'daily-brief',
    title: 'Daily Brief',
    minutes: 1,
    category: 'Planning',
    description: 'Wake up to the day already organized — weather, calendar, reminders and travel when relevant.',
    prompt: 'Today',
    steps: ['Choose your briefing time.', 'Keep WhatsApp briefing and email briefing independently on or off.', 'Use Today to turn the important parts into actions.'],
  },
  {
    key: 'meeting-recorder',
    title: 'Meetings with Gogo',
    minutes: 2,
    category: 'Meetings',
    description: 'Record a meeting, get the transcript, decisions and follow-ups, then turn actions into reminders.',
    prompt: 'Record meeting',
    steps: ['Start the AskGogo recorder from WhatsApp.', 'End the recording when the meeting is finished.', 'Review transcript, decisions and action items back in AskGogo.'],
  },
  {
    key: 'travel',
    title: 'Travel with Gogo',
    minutes: 1,
    category: 'Travel',
    description: 'Send a ticket or itinerary and let Gogo keep the travel details and timing close at hand.',
    steps: ['Send a ticket image or PDF.', 'Gogo extracts useful travel details.', 'Use Today and reminders around departure and check-in.'],
  },
  {
    key: 'personalize-gogo',
    title: 'Personalize Gogo',
    minutes: 1,
    category: 'Your Gogo',
    description: 'Choose how Gogo speaks to you and the small touches that make your calm space feel like yours.',
    steps: ['Open Personalize Gogo.', 'Choose the personality that feels right.', 'Pick the comfort drink beside Gogo and save your Gogo.'],
  },
  {
    key: 'breathing',
    title: 'Breathe with Gogo',
    minutes: 1,
    category: 'Calm',
    description: 'Three breathing patterns with original ambient sound for a short reset inside the dashboard.',
    steps: ['Tap the meditating Gogo button.', 'Choose Balance, Stress Reset or Deep Relax.', 'Turn sound on if you want the generated soundscape.'],
  },
  {
    key: 'memory-search',
    title: 'Search your second brain',
    minutes: 1,
    category: 'Memory',
    description: 'Search across what Gogo has learned and saved using the way you naturally remember it.',
    prompt: 'What do you remember about my saved documents?',
    steps: ['Ask naturally instead of browsing folders.', 'Use names, brands, dates, amounts or phrases as clues.', 'Open the relevant memory or original source when you need it.'],
  },
]
