import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const planner = readFileSync(new URL('../lib/agent/general-planner.ts', import.meta.url), 'utf8')
const missionTools = readFileSync(new URL('../lib/agent/mission-tools.ts', import.meta.url), 'utf8')
const calendarRead = readFileSync(new URL('../lib/agent/calendar-read.ts', import.meta.url), 'utf8')
const runRoute = readFileSync(new URL('../app/api/agent/run/route.ts', import.meta.url), 'utf8')
const executeRoute = readFileSync(new URL('../app/api/agent/runs/[id]/execute/route.ts', import.meta.url), 'utf8')

assert.match(planner, /const MAX_STEPS = 10/)
assert.match(planner, /Cover every explicit deliverable/i)
assert.match(planner, /Prefer safe, reversible work first/i)
assert.match(planner, /place the artifact after the safe preparatory work but BEFORE/i)
assert.match(planner, /'web_search'/)
assert.match(planner, /'artifact'/)
assert.doesNotMatch(planner, /GeneralPlanTool[\s\S]*\| 'payments'/)
assert.match(planner, /payments\/purchases are NOT an available planner tool/i)

assert.match(planner, /The plan sees ONLY this user request/i)
assert.match(planner, /User request: \$\{JSON\.stringify\(String\(text \|\| ''\)\.slice\(0, 1800\)\)\}/)
assert.match(planner, /messages: \[\{ role: 'user', content: prompt \}\]/)

assert.match(planner, /classifyAgentRequest\(step\.instruction\)/)
assert.match(planner, /evaluateAgentExecutionPolicy/)
assert.match(planner, /permissionFor\(tg,classified\.capability\)/)
assert.match(planner, /status:'waiting_approval'/)
assert.match(planner, /agent_approvals/)

assert.match(runRoute, /Date\.now\(\) - 90_000/)
assert.match(runRoute, /\.in\('status', \['queued','running','waiting_approval'\]\)/)
assert.match(runRoute, /metadata_json\?\.input_text/)
assert.match(runRoute, /handledBy: 'active-run-dedupe'/)
assert.match(runRoute, /deduplicated: true/)

assert.match(planner, /async function executeTaskStep/)
assert.match(planner, /from\('todos'\)/)
assert.match(planner, /verifiedStore:'todos'/)
assert.match(planner, /(?:create\|add).*or\\s\+verify/)
assert.match(planner, /if\\s\+it\\s\+does\\s\+not\\s\+already\\s\+exist/)
assert.match(planner, /if \(step\.tool === 'tasks'\) return executeTaskStep/)

assert.match(planner, /executeVerifiedMissionList/)
assert.match(planner, /if \(step\.tool === 'lists'\) return executeVerifiedMissionList/)
assert.match(missionTools, /getAllLists/)
assert.match(missionTools, /addToListDetailed/)
assert.match(missionTools, /getList/)
assert.match(missionTools, /verifiedStore:'lists'/)
assert.match(missionTools, /mission_list_write_unverified/)

assert.match(planner, /executeVerifiedMissionMemory/)
assert.match(planner, /executeVerifiedMissionReminder/)
assert.match(planner, /executeVerifiedMissionWebSearch/)
assert.match(planner, /executeVerifiedMissionCalendar/)
assert.match(planner, /missionText:params\.missionText/)
assert.match(planner, /missionText:params\.text/)
assert.match(planner, /missionText:String\(meta\.input_text\|\|''\)/)

assert.match(missionTools, /const exactDate=explicitDate\(step\.instruction\)/)
assert.match(missionTools, /const exactTime=explicitMissionClock\(step\.instruction\)/)
assert.match(missionTools, /persistMissionReminder/)
assert.match(missionTools, /from\('reminders'\)\.insert/)
assert.match(missionTools, /verifiedStore:'reminders'/)
assert.match(missionTools, /mission_reminder_write_unverified/)
assert.equal(new Date('2026-09-15T08:00:00+05:30').getTime() - 24 * 3600_000, new Date('2026-09-14T02:30:00Z').getTime())

assert.match(missionTools, /resultDatesAreInsideWindow/)
assert.match(missionTools, /dates\.every\(date=>date>=startDate&&date<=endDate\)/)
assert.match(missionTools, /mixedDateResultsRejected/)
assert.match(missionTools, /exactDateQuery/)
assert.match(missionTools, /dateRelevance==='matched'/)
assert.match(missionTools, /verifiedCuration:'travel-research'/)
assert.match(missionTools, /doc_type','ticket'/)
assert.match(missionTools, /verifiedRelevance:true/)
assert.match(missionTools, /No saved flight matched this mission/)

// Calendar mutations remain approval-bound and idempotent, while availability
// reads are a separate no-write implementation. This is the P0.8 safety invariant:
// “find me a free slot” must never create an event.
assert.match(planner, /if \(step\.tool === 'calendar'\)/)
assert.match(planner, /approvalAction:'calendar_change'/)
assert.match(planner, /executeVerifiedMissionCalendar/)
assert.match(missionTools, /isCalendarWriteStep/)
assert.match(missionTools, /if\(!isCalendarWriteStep\(params\.step\)\)/)
assert.match(missionTools, /executeReadOnlyCalendarStep/)
assert.match(calendarRead, /fetchPrimaryCalendarEvents/)
assert.match(calendarRead, /availableSlots/)
assert.match(calendarRead, /durationMinutes/)
assert.match(calendarRead, /mutated:false/)
assert.doesNotMatch(calendarRead, /method:\s*['"]POST['"]/)
assert.doesNotMatch(calendarRead, /createCalendarEvent/)
assert.match(calendarRead, /next week/)
assert.match(calendarRead, /9\*60/)
assert.match(calendarRead, /18\*60/)

assert.match(missionTools, /google_calendar_connected,google_refresh_token/)
assert.match(missionTools, /refreshAccessToken/)
assert.match(missionTools, /privateExtendedProperty:`askgogoRunId=\$\{params\.runId\}`/)
assert.match(missionTools, /extendedProperties:\{private:\{askgogoRunId:params\.runId/)
assert.match(missionTools, /start:\{date:startDate\},end:\{date:endExclusive\}/)
assert.match(missionTools, /verifiedStore:'google-calendar'/)

assert.match(planner, /export function missingMissionInput/)
assert.match(planner, /missionHasDeparture/)
assert.match(planner, /Choose the departure date and time first/i)
assert.match(planner, /'input_required'/)
assert.match(planner, /inputRequired:true/)
assert.match(planner, /status:'paused'/)

assert.match(planner, /placeArtifactBeforeDeferredWork/)
assert.match(planner, /steps\.splice\(deferredIndex, 0, artifact\)/)
assert.match(planner, /artifactTitleFromInstruction/)
assert.match(planner, /general_plan_artifact_update_failed/)

assert.match(planner, /params\.totalSteps/)
assert.match(planner, /params\.plan\.steps\.length/)
assert.match(planner, /resumeApprovedGeneralPlan/)
assert.match(planner, /execution_payload\?\.ordinal/)
assert.match(planner, /approvedOrdinal===ordinal/)
assert.match(planner, /from\('agent_artifacts'\)/)
assert.match(planner, /source_refs = \[\{type:'agent_run',id:runId\}\]/)

const travelCalendarCall = runRoute.lastIndexOf('tryPrepareTravelCalendarPlan')
const expiryCall = runRoute.lastIndexOf('tryRunExpiryReminderPlan')
const generalCall = runRoute.lastIndexOf('tryRunGeneralPlan')
const travelResearchCall = runRoute.lastIndexOf('tryRunTravelResearch')
const fallbackCall = runRoute.lastIndexOf('runAgentCommand')
assert.ok(travelCalendarCall >= 0 && expiryCall >= 0 && generalCall >= 0 && travelResearchCall >= 0 && fallbackCall >= 0)
assert.ok(generalCall > travelCalendarCall)
assert.ok(generalCall > expiryCall)
assert.ok(generalCall < travelResearchCall, 'multi-step planner must run before simple travel research')
assert.ok(generalCall < fallbackCall, 'general planner must run before simple fallback')

assert.match(executeRoute, /planType === 'general_multi_tool'/)
assert.match(executeRoute, /resumeApprovedGeneralPlan/)

console.log('agent general planner + read-only calendar availability verification passed')
