import assert from 'node:assert/strict'
import fs from 'node:fs'

const closure = fs.readFileSync('lib/agent/booking-closure.ts','utf8')
const queue = fs.readFileSync('lib/agent/booking-queue.ts','utf8')
const closureWorker = fs.readFileSync('lib/agent/booking-closure-worker.ts','utf8')
const ticketReader = fs.readFileSync('lib/agent/secure-ticket-reader.ts','utf8')
const providerChallenge = fs.readFileSync('lib/agent/provider-challenge.ts','utf8')
const gmail = fs.readFileSync('lib/agent/gmail-ticket-credential.ts','utf8')
const calendar = fs.readFileSync('lib/agent/booking-calendar-execution.ts','utf8')
const feature = fs.readFileSync('lib/feature-intents.ts','utf8')
const whatsapp = fs.readFileSync('lib/agent/whatsapp-bridge.ts','utf8')
const executeRoute = fs.readFileSync('app/api/agent/runs/[id]/execute/route.ts','utf8')
const watcher = fs.readFileSync('lib/agent/booking-change-worker.ts','utf8')
const cron = fs.readFileSync('app/api/cron/booking-events/route.ts','utf8')
const vercel = JSON.parse(fs.readFileSync('vercel.json','utf8')) as { crons?: Array<{path:string;schedule:string}> }

assert.match(ticketReader,/navigator,'share'/)
assert.match(ticketReader,/__gogoShareData/)
assert.match(ticketReader,/const useful=.*share.*download.*show ticket.*view ticket.*ticket.*qr.*barcode.*pass.*wallet/i)
assert.match(ticketReader,/isMobile:true/)
assert.match(ticketReader,/hasTouch:true/)
assert.match(ticketReader,/viewport:\{width:412,height:915\}/)
assert.match(ticketReader,/mobileUA=/)
assert.match(ticketReader,/waitForTicket/)
assert.match(ticketReader,/booking id/)
assert.match(ticketReader,/SECURE_TICKET_READER_RESULT/)
assert.match(ticketReader,/SECURE_TICKET_READER_PROVIDER_CHALLENGE/)
assert.match(ticketReader,/PROVIDER_CLOUDFLARE_CHALLENGE/)
assert.match(ticketReader,/DEVICE_HANDOFF_REQUIRED/)
assert.match(ticketReader,/screenshot\(\{type:'png'/)
assert.match(ticketReader,/provider_page/)
assert.match(ticketReader,/human_auth_required/)

assert.match(providerChallenge,/attention required!.*cloudflare/i)
assert.match(providerChallenge,/sorry, you have been blocked/i)
assert.match(providerChallenge,/cloudflare ray id/i)
assert.match(providerChallenge,/provider_cloudflare_challenge/)
assert.match(providerChallenge,/device_handoff_required/)
assert.match(closureWorker,/BOOKING_PROVIDER_DEVICE_HANDOFF_REQUIRED/)
assert.match(closureWorker,/provider_cloudflare_challenge/)
assert.match(closureWorker,/deviceHandoffRequired:true/)
assert.match(closureWorker,/status:'blocked'/)
assert.match(closureWorker,/due_at:null/)

assert.match(gmail,/gmail_connected/)
assert.match(gmail,/verifyImageCredential/)
assert.match(gmail,/TICKET_CREDENTIAL/)
assert.match(gmail,/Logos, posters, banners and marketing images are OTHER/)
assert.match(gmail,/filenameEvidence/)
assert.doesNotMatch(gmail,/method:\s*['"](?:POST|PATCH|DELETE)['"]/)

assert.match(feature,/queueBookingClosure/)
assert.doesNotMatch(feature,/await closeBookingLink/)
assert.match(queue,/action_key:\s*'booking-closure'/)
assert.match(queue,/status:\s*'ready'/)
assert.match(closureWorker,/closeBookingLink/)
assert.match(closureWorker,/sendWhatsAppMediaMessage/)
assert.match(cron,/processQueuedBookingClosures/)
const bookingCron = (vercel.crons || []).find(x => x.path === '/api/cron/booking-events')
assert.equal(bookingCron?.schedule, '* * * * *', 'booking closure queue must run every minute')

assert.match(closure,/TRUSTED_PROVIDER_HOSTS/)
assert.match(closure,/redirect:'manual'/)
assert.match(closure,/trustedProviderUrl\(next\)/)
assert.doesNotMatch(closure,/redirect:\s*['"]follow['"]/)

assert.match(closure,/details\.status==='confirmed'\|\|details\.status==='rescheduled'/)
assert.match(closure,/details\.status==='cancelled'/)
assert.match(closure,/details\.status==='unknown'/)
assert.match(closure,/ensureReminder/)
assert.match(closure,/prepareBookingCalendarApproval/)
assert.match(closure,/booking-change-watch/)
assert.match(closure,/providerIssued:true/)
assert.match(closure,/retrieveEventCredential\(telegramId:number,requestText:string\)/)
assert.match(closure,/queryTokens\(requestText\)/)
assert.doesNotMatch(closure,/generate.*qr/i)

assert.match(calendar,/existingPending/)
assert.match(calendar,/eventIdForLifeEvent/)
assert.match(calendar,/booking-life-event:/)
assert.match(calendar,/action_type:'calendar_change'/)
assert.match(calendar,/eq\('status','approved'\)/)
assert.match(calendar,/create_booking_calendar_event/)
assert.doesNotMatch(calendar,/sendUpdates=all/)

assert.match(whatsapp,/booking_event_calendar/)
assert.match(whatsapp,/executeApprovedBookingCalendar/)
assert.match(executeRoute,/booking_event_calendar/)
assert.match(executeRoute,/executeApprovedBookingCalendar/)

assert.match(watcher,/lifecycle_state:cancelled\?'cancelled':'watching'/)
assert.doesNotMatch(watcher,/needs_attention/)
assert.match(watcher,/cancellationNotified:true/)
assert.match(watcher,/await complete\(row\.id/)
assert.match(watcher,/sendAgentPush/)
assert.match(cron,/CRON_SECRET/)
assert.match(cron,/processBookingChangeWatches/)

console.log('✅ Booking closure regression passed: mobile provider ticket + Cloudflare device handoff + verified Gmail + calendar + reminder + retrieval + change watch')
