import assert from 'node:assert/strict'
import fs from 'node:fs'

const worker = fs.readFileSync('lib/agent/life-event-worker.ts', 'utf8')
const execution = fs.readFileSync('lib/agent/life-event-execution.ts', 'utf8')
const executeRoute = fs.readFileSync('app/api/agent/runs/[id]/execute/route.ts', 'utf8')
const whatsappBridge = fs.readFileSync('lib/agent/whatsapp-bridge.ts', 'utf8')
const cronRoute = fs.readFileSync('app/api/cron/life-events/route.ts', 'utf8')
const checkinMigration = fs.readFileSync('supabase/life-events-v2-checkin-url.sql', 'utf8')
const vercel = fs.readFileSync('vercel.json', 'utf8')

assert.match(worker, /prepare-web-checkin/)
assert.match(worker, /runSecureBrowser/)
assert.match(worker, /mode:\s*'draft'/)
assert.match(worker, /evaluateAgentExecutionPolicy/)
assert.match(worker, /evaluateAgentSentinel/)
assert.match(worker, /agent_permissions/)
assert.match(worker, /capability:\s*'browser'/)
assert.match(worker, /Do not submit check-in/)
assert.match(worker, /Do not purchase (?:a paid |a )?seat or add-on/)
assert.match(worker, /checkin-submit-approval/)
assert.match(worker, /action_type:\s*'booking'/)
assert.match(worker, /Free allocation only/)
assert.match(worker, /No paid seat\/add-on without separate approval/)
assert.match(worker, /human_auth_required/)
assert.match(worker, /password, OTP, CAPTCHA, passkey/i)
assert.match(worker, /deferAction\(action, DEFER_PENDING_EXECUTOR_MINUTES/)
assert.match(worker, /due_at:\s*dueAt/)
assert.match(worker, /eq\('status', 'running'\)/)
assert.match(worker, /staleBefore/)
assert.match(worker, /reclaimed/)

// Booking reference can be used transiently inside the isolated browser objective,
// but the run metadata must only record that it exists, not the value itself.
assert.match(worker, /confirmation_ref_present:\s*true/)
assert.doesNotMatch(worker, /metadata:\s*\{[^}]*confirmationRef:/s)

assert.match(execution, /life_event_checkin/)
assert.match(execution, /evaluateAgentExecutionPolicy/)
assert.match(execution, /evaluateAgentSentinel/)
assert.match(execution, /agent_permissions/)
assert.match(execution, /approvalStatus:\s*'approved'/)
assert.match(execution, /irreversible:\s*true/)
assert.match(execution, /approved:\s*true/)
assert.match(execution, /eq\('status',\s*'approved'\)/)
assert.match(execution, /eq\('status', 'queued'\)/)
assert.match(execution, /agent_run_already_claimed/)
assert.match(execution, /hasCheckinSuccessEvidence/)
assert.match(execution, /kind === 'submit' && a\.status === 'done'/)
assert.match(execution, /checkin_confirmation_not_verified/)
assert.match(execution, /Use free seat allocation only/)
assert.match(execution, /Do not buy baggage, meals, upgrades, insurance, priority boarding/)
assert.match(execution, /mode:\s*'execute'/)
assert.match(execution, /human_auth_required/)
assert.match(execution, /status:\s*'executed'/)
assert.match(execution, /lifecycle_state:\s*'watching'/)

// SQL-promoted tickets must receive a checkInUrl for the exact carriers whose
// deep links are verified in the TypeScript airline registry. Unknown carriers
// remain unset so the browser worker fails closed instead of inventing a URL.
assert.match(checkinMigration, /when '6E' then 'https:\/\/www\.goindigo\.in\/web-check-in\.html'/)
assert.match(checkinMigration, /when 'AI' then 'https:\/\/www\.airindia\.com\/in\/en\/manage\/web-checkin\.html'/)
assert.match(checkinMigration, /when 'IX' then 'https:\/\/www\.airindiaexpress\.com\/checkin-home'/)
assert.match(checkinMigration, /when 'EY' then 'https:\/\/www\.etihad\.com\/en\/manage\/check-in'/)
assert.match(checkinMigration, /checkInUrlVerified/)
assert.match(checkinMigration, /Backfill existing promoted flights/)

assert.match(executeRoute, /executeApprovedLifeEventCheckin/)
assert.match(executeRoute, /planType === 'life_event_checkin'/)
assert.match(whatsappBridge, /executeApprovedLifeEventCheckin/)
assert.match(whatsappBridge, /planType === 'life_event_checkin'/)
assert.match(cronRoute, /CRON_SECRET/)
assert.match(cronRoute, /processDueLifeEventActions/)
assert.match(vercel, /\/api\/cron\/life-events/)
assert.match(vercel, /\*\/5 \* \* \* \*/)

console.log('✅ Life Event background executor regression passed')
